/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VContent: typeof import('vuetify/lib')['VContent']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VPagination: typeof import('vuetify/lib')['VPagination']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
